name: BanHammer
version: 1.0.0
main: de.raspifreak.banhammer.BanHammer
website: http://www.raspifreak.de/
description: Das ist ein BanHammer Plugin für Guenni3
author: RaspiFreak

commands:
  banhammer:
    description: Gibt dir den BanHammer
    usage: /<command>
    aliases: [bh]