name: BanHammer
version: 1.0.0
main: de.raspifreak.banhammer.BanHammer
website: http://www.raspifreak.de/
description: This is a BanHammer Plugin for Guenni3
authors: [RaspiFreak]

commands:
  banhammer:
    description: Gives you the banhammer
    usage: /<command>
    aliases: [bh]